// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: algolens.proto

package algolenspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_algolens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_algolens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_algolens_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type Hit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Statement     string                 `protobuf:"bytes,6,opt,name=statement,proto3" json:"statement,omitempty"`
	Patterns      []string               `protobuf:"bytes,7,rep,name=patterns,proto3" json:"patterns,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,8,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Score         float64                `protobuf:"fixed64,9,opt,name=score,proto3" json:"score,omitempty"`
	MatchedTerms  []string               `protobuf:"bytes,10,rep,name=matched_terms,json=matchedTerms,proto3" json:"matched_terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_algolens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_algolens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_algolens_proto_rawDescGZIP(), []int{1}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Hit) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Hit) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Hit) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Hit) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *Hit) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *Hit) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Hit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetMatchedTerms() []string {
	if x != nil {
		return x.MatchedTerms
	}
	return nil
}

type SearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hits  []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// server-measured, excludes RPC overhead
	ScoringLatencyMs float64 `protobuf:"fixed64,2,opt,name=scoring_latency_ms,json=scoringLatencyMs,proto3" json:"scoring_latency_ms,omitempty"`
	Ranker           string  `protobuf:"bytes,3,opt,name=ranker,proto3" json:"ranker,omitempty"`
	CorpusSize       int32   `protobuf:"varint,4,opt,name=corpus_size,json=corpusSize,proto3" json:"corpus_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_algolens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_algolens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_algolens_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResponse) GetScoringLatencyMs() float64 {
	if x != nil {
		return x.ScoringLatencyMs
	}
	return 0
}

func (x *SearchResponse) GetRanker() string {
	if x != nil {
		return x.Ranker
	}
	return ""
}

func (x *SearchResponse) GetCorpusSize() int32 {
	if x != nil {
		return x.CorpusSize
	}
	return 0
}

var File_algolens_proto protoreflect.FileDescriptor

const file_algolens_proto_rawDesc = "" +
	"\n" +
	"\x0ealgolens.proto\x12\balgolens\"3\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"\x87\x02\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1c\n" +
	"\tstatement\x18\x06 \x01(\tR\tstatement\x12\x1a\n" +
	"\bpatterns\x18\a \x03(\tR\bpatterns\x12\x1d\n" +
	"\n" +
	"source_url\x18\b \x01(\tR\tsourceUrl\x12\x14\n" +
	"\x05score\x18\t \x01(\x01R\x05score\x12#\n" +
	"\rmatched_terms\x18\n" +
	" \x03(\tR\fmatchedTerms\"\x9a\x01\n" +
	"\x0eSearchResponse\x12!\n" +
	"\x04hits\x18\x01 \x03(\v2\r.algolens.HitR\x04hits\x12,\n" +
	"\x12scoring_latency_ms\x18\x02 \x01(\x01R\x10scoringLatencyMs\x12\x16\n" +
	"\x06ranker\x18\x03 \x01(\tR\x06ranker\x12\x1f\n" +
	"\vcorpus_size\x18\x04 \x01(\x05R\n" +
	"corpusSize2I\n" +
	"\x06Search\x12?\n" +
	"\n" +
	"SearchTopK\x12\x17.algolens.SearchRequest\x1a\x18.algolens.SearchResponseB\x1bZ\x19algolens/proto;algolenspbb\x06proto3"

var (
	file_algolens_proto_rawDescOnce sync.Once
	file_algolens_proto_rawDescData []byte
)

func file_algolens_proto_rawDescGZIP() []byte {
	file_algolens_proto_rawDescOnce.Do(func() {
		file_algolens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_algolens_proto_rawDesc), len(file_algolens_proto_rawDesc)))
	})
	return file_algolens_proto_rawDescData
}

var file_algolens_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_algolens_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: algolens.SearchRequest
	(*Hit)(nil),            // 1: algolens.Hit
	(*SearchResponse)(nil), // 2: algolens.SearchResponse
}
var file_algolens_proto_depIdxs = []int32{
	1, // 0: algolens.SearchResponse.hits:type_name -> algolens.Hit
	0, // 1: algolens.Search.SearchTopK:input_type -> algolens.SearchRequest
	2, // 2: algolens.Search.SearchTopK:output_type -> algolens.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_algolens_proto_init() }
func file_algolens_proto_init() {
	if File_algolens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_algolens_proto_rawDesc), len(file_algolens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_algolens_proto_goTypes,
		DependencyIndexes: file_algolens_proto_depIdxs,
		MessageInfos:      file_algolens_proto_msgTypes,
	}.Build()
	File_algolens_proto = out.File
	file_algolens_proto_goTypes = nil
	file_algolens_proto_depIdxs = nil
}
